# GitHub Pages configuration for Workshop Landing Page
title: "Agentic AI Fundamentals for Product Managers"
description: "Workshop registration page for learning agentic AI development using low-code/no-code tools"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - workshop-landing-page/
  - workshop-landing-page-plan.md
  - LICENSE
  - node_modules/
  - vendor/

# SEO settings
url: "https://workatplay-admin.github.io"
baseurl: "/roo-demo"

# Social media and contact
email: info@agenticai-workshop.com